version: '3'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db
    links:
      - postgres-db
    environment:
      - DATABASE_URL=postgresql://postgres:pass123@postgresdatabase:5432/mydb
    
  postgres-db:
    image: postgres:latest
    container_name: postgresdatabase
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

    
